name: Build and Push Frontend Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

# Разрешения
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Зависимости и сборка
      - name: Install and Build Node app
        run: |
          npm install
          npm run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Lowercase Repo Name
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      # Собираем и отправляем докер образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}:latest
            ghcr.io/${{ env.REPO_LC }}:sha-${{ github.sha }}
      
      # Деплой на Azure
      - name: Login to Azure
        uses: azure/login@v2
        continue-on-error: true
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        continue-on-error: true
        with:
          app-name: Allaandra-KPZ-App
          images: ghcr.io/${{ env.REPO_LC }}:latest